import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

//Colatz functions
import { createData } from '../../src/colatz'

//Chart
import { LineChart, Line, CartesianGrid, XAxis, YAxis } from 'recharts';

//Render the chart

function DataRender(props){
  let data = createData(props.number);

  return (
    <LineChart width={600} height={300} data={data}>
      <Line type="monotone" dataKey="y" stroke="#8884d8" />
      <CartesianGrid stroke="#ccc" />
      <XAxis dataKey="name" />
      <YAxis />
    </LineChart>
  )
}


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
       <DataRender number={77031} />
      </div>
    </div>
  )
}
